### ISSUE TITLE
Doctrine Adapter's "getItem()" behaves incorrect

### ISSUE THREAD

**Issue by scento** [egils/Cache#1]
The doctrine adapter does not return an Instance of `Psr\Cache\CacheItemInterface`, when calling `getItem()` with an not-existing key, but instead `false`. The [specifications](https://github.com/php-fig/fig-standards/blob/master/proposed/cache.md) especially refer to this way to request an instance.

A better solution would be an implementation for `getItem()` like this:

``` php
if ($this->provider->contains($key) === true) {
      $item = $this->provider->fetch($key);
      $item->setHit(true);
      return $item;
} else {
      return new CacheItem($key);
}
```

**Comment by egils** [comment]
Very good catch! Will fix that by the end of the day. 

Thank you for your contribution! :+1:
